server:
  port: 9000
mybatis:
  configuration:
    map-underscore-to-camel-case: true
  mapper-locations: classpath*:mybatis/**/*Mapper.xml
saluki:
  grpc:
    registryAddress: localhost:8500
  dubbo:
    registryAddress: zookeeper://224.0.0.0:1111